import type { NextPage } from 'next';
import Head from 'next/head';
import { PictureMaker } from '../components/PictureMaker';
import classes from '../styles/home.module.scss';

const Home: NextPage = () => {
  return (
    <div className={classes.container}>
      <Head>
        <title>Silver Octo Pancake</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={classes.main}>
        <header>
          <h1>טקסט חופשי לתמונה</h1>
          {/*  eslint-disable-next-line react/no-unescaped-entities */}
          <p>מונע ע"י stable-diffusion</p>
        </header>
        <PictureMaker />
      </main>
    </div>
  );
};

export default Home;
